package de.smahoo.jwave.io;

public enum JWaveDatagramStatus {
	STATUS_GENERATED,
	STATUS_RECEIVED,
	STATUS_TRANSMITTED,
	STATUS_TRANSMITTING,
	STATUS_WAITING_FOR_WAKEUP_NOTIFICATION,
	STATUS_TRANSMISSION_FAILED;
}
